# Generated by Django 3.2.8 on 2021-11-02 12:59

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Live_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniq_userid', models.CharField(blank=True, max_length=20)),
                ('profile_pic', models.ImageField(upload_to='profile_pics', verbose_name='Profile Pic')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Live_User',
                'verbose_name_plural': 'Live_Users',
                'ordering': ['uniq_userid'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=600)),
                ('room_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('thumbnail', models.ImageField(upload_to='room_pics', verbose_name='Group Dp')),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
                'ordering': ['room_id'],
            },
        ),
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField()),
                ('last_logout', models.DateTimeField()),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.room')),
                ('uniq_userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.live_user')),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
                'ordering': ['uniq_userid', 'room_id'],
            },
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=200000)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime(2021, 11, 2, 18, 29, 40, 68479))),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.room')),
                ('uniq_userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.live_user')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['-date'],
            },
        ),
    ]
