# Generated by Django 3.2.8 on 2021-11-02 18:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20211102_1850'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptions',
            options={'ordering': ['room_ref', 'lu_ref'], 'verbose_name': 'Subscription', 'verbose_name_plural': 'Subscriptions'},
        ),
        migrations.RenameField(
            model_name='messages',
            old_name='uniq_userid',
            new_name='lu_ref',
        ),
        migrations.RenameField(
            model_name='messages',
            old_name='room_id',
            new_name='room_ref',
        ),
        migrations.RenameField(
            model_name='subscriptions',
            old_name='uniq_userid',
            new_name='lu_ref',
        ),
        migrations.RenameField(
            model_name='subscriptions',
            old_name='room_id',
            new_name='room_ref',
        ),
        migrations.AlterField(
            model_name='messages',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 11, 2, 23, 32, 33, 58169)),
        ),
    ]
