# Generated by Django 3.2.8 on 2021-11-02 18:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_auto_20211102_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 11, 2, 23, 33, 26, 333442)),
        ),
    ]
