# Generated by Django 3.2.8 on 2021-11-22 16:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_alter_messages_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptions',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='subscriptions',
            name='last_logout',
        ),
        migrations.AddField(
            model_name='subscriptions',
            name='last_visited',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='messages',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 11, 22, 21, 52, 4, 734454)),
        ),
    ]
